package mk.ukim.finki.soa.masterthesis.model.valueObject

import java.io.Serializable

enum class AppRole(val roleName: String) : Serializable {
    PROFESSOR("ROLEPROFESSOR"),
    ADMIN("ROLEADMIN"),
    GUEST("ROLEGUEST"),
    STUDENT("ROLESTUDENT"),
    ACADEMIC_AFFAIR_VICE_DEAN("ROLEACADEMIC_AFFAIR_VICE_DEAN"),
    SCIENCE_AND_COOPERATION_VICE_DEAN("ROLESCIENCE_AND_COOPERATION_VICE_DEAN"),
    FINANCES_VICE_DEAN("ROLEFINANCES_VICE_DEAN"),
    DEAN("ROLEDEAN"),
    STUDENT_ADMINISTRATION("ROLESTUDENT_ADMINISTRATION"),
    STUDENT_ADMINISTRATION_MANAGER("ROLESTUDENT_ADMINISTRATION_MANAGER"),
    FINANCE_ADMINISTRATION("ROLEFINANCE_ADMINISTRATION"),
    FINANCE_ADMINISTRATION_MANAGER("ROLEFINANCE_ADMINISTRATION_MANAGER"),
    LEGAL_ADMINISTRATION("ROLELEGAL_ADMINISTRATION"),
    ARCHIVE_ADMINISTRATION("ROLEARCHIVE_ADMINISTRATION"),
    ADMINISTRATIONMANAGER("ROLEADMINISTRATIONMANAGER"),
    EXTERNAL("ROLEEXTERNAL");
}
