package mk.ukim.finki.soa.masterthesis.model.valueObject

import java.io.Serializable

enum class MasterThesisDocumentType(val documentType: String) : Serializable {
    THESIS_JUSTIFICATION("THESIS_JUSTIFICATION"),
    PLAN_AND_LITERATURE_REVIEW("PLAN_AND_LITERATURE_REVIEW"),
    STUDENT_BIOGRAPHY("STUDENT_BIOGRAPHY"),
    THESIS_TEXT("THESIS_TEXT"),
    REPORT("REPORT"),
    THESIS_TEXT_OLD_VERSION("THESIS_TEXT_OLD_VERSION"),
    EXTENDED_DUE_DATE("EXTENDED_DUE_DATE"),
    SECRETARY_VALIDATION("SECRETARY_VALIDATION"),
    SECOND_SECRETARY_VALIDATION("SECOND_SECRETARY_VALIDATION"),
    FOURTH_SECRETARY_VALIDATION("FOURTH_SECRETARY_VALIDATION");
}
